 
name: RAE ROS CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
env:
  ROS_DISTRO: iron

jobs:
  docker-build:
    name: Build and Upload to Docker Hub
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env: 
      PUSH: ${{ (github.repository == 'luxonis/rae-ros') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.PUSH == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Get Version
        if: env.PUSH == 'true'
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and Push 
        uses: docker/build-push-action@v3
        if: env.PUSH == 'true'
        with:
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            USE_RVIZ=1
          platforms: |
            amd64
            arm64
          push: ${{ env.PUSH }}
          no-cache: true
          tags: | 
            luxonis/depthai-ros-rae-iron
      
